### model
model_name_or_path: /home/aiscuser/huggingface_models/Qwen/Qwen3-14B
trust_remote_code: true
enable_thinking: false

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]
flash_attn: fa2

### dataset
dataset: from_ai_npc_v3
template: qwen3
cutoff_len: 4096
max_samples: 1000000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4
# tokenized_path: /home/aiscuser/sony-cpdc/output/qwen2.5-7b_sft_tokenized

### output
output_dir: /home/aiscuser/LLaMA-Factory/saves/qwen3-14b_full_sft_from_ai_npc_v3_0626
logging_steps: 10
# save_steps: 1000
save_strategy: epoch
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: wandb  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.05
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
# eval_dataset: alpaca_en_demo
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
